FROM node:18-alpine AS base

WORKDIR usr/src/app

COPY package*.json .

RUN npm install -g @angular/cli

COPY . .

FROM base AS develop

RUN npm install

VOLUME /usr/src/app/node_modules

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "500"]
