FROM node:20-bullseye AS base

WORKDIR usr/src/app

COPY package*.json .

RUN npm install -g @angular/cli

RUN npm install

COPY . .

FROM base AS builder

WORKDIR usr/src/app

RUN npm run build:prod

FROM nginx:alpine AS prod

COPY --from=builder /usr/src/app/docs /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
